"""Matrice documentaire versionnée : aucune modification de l'application."""
import collections, json, re
from pathlib import Path
OUT=Path(__file__).resolve().parent.parent
# id | composant | chemin/service | classe proposée (vide=inconnue) | preuve/statut |
# exigences | priorité/phase | charge basse-haute j6h | contribution | donnée/risque | dépendance | retour
DATA='''
M01|Baseline Git et branches|.git ; deux worktrees|KEEP|V S04/S05 : HEAD distant identique et inventaire des fichiers ; conservation des références|AUD-01 GOV-01|P0/F0|0-0.25|Historique préservé, PR12/13 fusionnées|Code et historique ; perte par reset/nettoyage|Aucune mutation prévue|Ne rien supprimer ; retrouver chaque commit et fichier par manifeste
M02|Garde-fous et CI|GitHub main ; .github/workflows|IMPROVE|V S13 : protected=false et 0 workflow ; convention PR existante|GOV-01 REC-01 SEC-04|P0/F0|1-2|Convention de revue documentée, CI absente|Code ; publication non contrôlée|Droits GitHub et checks pertinents|Désactiver nouveau workflow défaillant, conserver revues et version précédente
M03|Documentation et préséance|CLAUDE.md ; README.md ; docs/handoff/|IMPROVE|V S02/S03 : dates, stack verrouillée et instructions anciennes en conflit avec cibles|AUD-01 AUD-02 GOV-01|P0/F0|0.5-2|Passation et doctrine riches mais datées|Décisions ; erreur de périmètre ou de manipulation|Arbitrage Alain|Historique Git des documents ; archiver sans effacer les décisions antérieures
M04|Référence créative archivée|docs/charte-graphique/reference-v3/|KEEP|V S05/S10 : fichiers et empreintes contrôlés ; conservation comme source, pas validation du rendu final|CAT-01 UX-01|P1/F1|0-0.5|Livraison Manus intégrée et corrections Claude tracées|Référence créative ; perte d'intention|Arbitrage créatif séparé|Conserver source d'origine et tracer les adaptations
M05|Identité de marque|brand/koinoborihouse/|KEEP|V S05 : neuf fichiers présents ; KEEP limité à la préservation binaire, droits NV|CAT-01 PRD-01|P1/F1|0-0.5|Logos et favicon existants conservés|Images publiques ; mauvais logo ou droits incomplets|Validation créative et droits|Restaurer binaire de référence par SHA-256
M06|Masters et fichiers ignorés|Koinobori_House_Assets_Claude/ ; prototypes ; logs|KEEP|V S05 : inventoriés ; stockage de sauvegarde externe NV|AUD-01 SEC-04|P0/F0|0.5-1|Pack Manus et matériaux de travail locaux|Actifs irremplaçables ; perte disque|Copie privée externe|Aucune suppression ; copie externe et contrôle d'empreinte à vérifier
M07|WordPress cœur et base|Production et staging|IMPROVE|V S06/S16 : WP7.1 annoncé prod et état WC staging ; PHP8.3.33 MariaDB11.4.13 staging ; checksums/config complets NV ; V S19 : racines/bases identifiées et checksums cœur conformes sur les deux sites ; fichiers error_log supplémentaires à contrôler|ARC-01 COM-01 SEC-04|P0/F0|0.5-1.5|Installation déclarée, cœur hors Git|Identités et contenus ; incompatibilité ou perte|Accès serveur et clone|Snapshot cohérent et version applicative compatible, drill obligatoire
M08|WooCommerce et autorité commerce|Plugin WC ; commandes ; HPOS|IMPROVE|V S16 : WC11.1.0, base11.1.0-1, HPOS actif ; blocs panier/checkout ; transactions NV ; V S17 : panier anglais vide partiellement français ; V S19 : absent de production ; staging HPOS 4 checkout-draft et 1 completed, nature réelle/test non établie|COM-01 ORD-01 DAT-01|P0/F1|1-3|Catalogue et synchronisation déclarés|Commandes/paiements/stock ; double moteur ou perte|Inventaire plugins et paiements sandbox|Retour applicatif compatible ; réconcilier commandes récentes avant tout retour de base
M09|Polylang et Polylang for WC|Plugins i18n et tables de liaison|IMPROVE|V S16/F05 : PLL3.8.7 et PLLWC2.2.4, racines FR/EN blog vide mais pages longues présentes ; cause NV ; V S17 : trois paires légales/USA présentes sans liaison affichée|SEO-01 INT-01 COM-01|P0/F1|0.5-2|Paramétrage et essais historiques|Liens langues et stock ; duplication ou rupture URLs|Clone, versions, liaisons et options|Conserver IDs et paires ; restaurer réglages précis avec relevé avant/après
M10|SEOPress et sitemaps|Plugin SEO ; métadonnées|IMPROVE|V S16 : SEOPress10.2, canonical accueil vers racine en désaccord de rendu ; sitemap exhaustif NV|SEO-01 SEO-02 INT-01|P1/F1|0.5-1.5|Choix et scripts de recette documentés|Indexation ; canonical ou sitemap erroné|Crawl authentifié et historique URLs|Rétablir métadonnées et redirections ; ne pas lever noindex avant recette
M11|Kadence parent / Blocks|Thème parent ; plugin de blocs|IMPROVE|V S16 : Kadence1.5.2 staging, classique ; aucun Kadence Blocks dans14 extensions ; licence NV ; V S19 : parent production 1.5.0 confirmé par WP-CLI ; conserver le socle et vérifier compatibilité sur clone|UX-01 ARC-01|P1/F1|0.5-1.5|Socle existant, contenu Gutenberg annoncé|Présentation/contenu ; incompatibilité après mise à jour|Versions serveur et clone|Version parent précédente et données de blocs préservées
M12|Intégration PHP du thème enfant|wp/themes/koinobori-child/functions.php|IMPROVE|V S16/F02 : staging1.1.0 mais charte v3 non liée, dépôt la charge ; identité release non fiable ; V S19 : functions.php différent après normalisation CRLF/LF ; charte v3 absente du staging ; lint PHP réussi|UX-01 GOV-02 REC-01|P1/F1|0.5-1.5|Fondations, preloads et palette avec repli|Présentation ; dérive éditeur/front et ordre CSS|WP/Kadence et recette checkout|Retour au fichier précédent sans toucher aux commandes
M13|Feuilles de style dupliquées|kh-foundations.css ; kh-charte-v3.css ; reference-v3/styles.css|REFACTOR|V S05/F08 : égalité après normalisation URL ; dette démontrée|UX-01 UX-02 GOV-01|P1/F1|1-3|Portage Manus et corrections Claude|CSS ; dérive entre source et thème|Tests visuels et périmètre marchand|Garder artefact CSS antérieur ; mêmes sélecteurs et rendu contractuel
M14|Palette / contraste / liens|theme.json ; CSS ; fallback functions.php|IMPROVE|V S05/F09 : or inférieur aux seuils textuels, kh-white absent éditeur ; V S19 : theme.json staging diffère réellement du dépôt après normalisation CRLF/LF|UX-02|P1/F1|0.5-2|Palette bornée et repli existants|Lisibilité ; liens indiscernables si kh-page global|Arbitrage couleurs et vrais gabarits|Revenir aux tokens précédents ; publier seulement après recette accessible
M15|Assemblages de pages versionnés|wp/themes/koinobori-child/ : patterns/templates absents|BUILD|V S05/F08 : aucun assemblage versionné ; classe limitée au dépôt, blocs en base NV|UX-01 CAT-01 SEO-01|P1/F1|3-8|CSS livré ; assemblage non livré en code|Pages/menus ; écrasement des contenus saisis|Export des blocs existants et arbitrage navigation 2027|Désactiver nouveaux patterns ; conserver pages et templates précédents
M16|Header Shoji et navigation|header-shoji-koino-v1.src.html ; .html|IMPROVE|V F07/S16 : prototype liens # ; menu staging sept entrées, Accueil /fr/ différent du lien logo /fr/accueil/|UX-01 UX-02 INT-01|P1/F1|1-3|Prototype existant, présentation à préserver|Navigation/compte/panier ; faux liens|Menus serveur, intégration accessible|Revenir au header existant ; conserver menus et identifiants
M17|Polices et outil de préparation|assets/fonts/ ; tools/fetch-fonts.py|IMPROVE|V S05/F09 : 21 WOFF2 ; chemin Windows codé, sources main non figées, licences à réunir|UX-01 OPS-01 PRD-01|P1/F1|0.5-1.5|Self-host et sous-ensembles JP|Actifs ; non-reproductibilité et droits incomplets|Provenance/version/licences et couverture glyphes|Conserver WOFF2 validés et checksums avant régénération
M18|Médias du thème et produits|assets/images/ ; catalog/images/|IMPROVE|V S05/F09 : 13 images thème, formats WebP ; poids élevés de certains masters Web|CAT-02 UX-01 OPS-01|P1/F1|1-3|Conversions et visuels créatifs existants|Images publiques ; qualité/performance/représentativité|Photos réelles et droits ; mesures de pages|Conserver originaux et variantes ; revenir au mapping précédent
M19|Routage racine|wp/mu-plugins/koino-lang-redirect.php|IMPROVE|V S16 : MU routage1.1.0 seul chargé ; code relu, variantes REST/query/cookies non recettées ; V S19 : fichier staging identique au dépôt après normalisation, lint réussi ; absent de production|INT-01 SEO-01 ARC-03|P1/F1|0.5-1.5|KH-107 chargé avant Polylang|URLs/cookies ; redirection parasite|WP/PLL versions ; tests root/REST/checkout|Ancien MU-plugin et config précédents ; ne pas casser accès /fr /en
M20|Correction signature BCDG|wp/mu-plugins/koino-bcdg-hyphen.php|IMPROVE|V S16/F10 : absent de la liste MU staging ; correctif1.1.0 local, tests intégration NV ; V S19 : absence du fichier confirmée dans les deux racines|CAT-02 SEO-01 REC-01|P1/F1|0.25-1|Correctif et revue du 09/09|Rendu texte ; correction appliquée au mauvais contexte|PHP/WP/SEOPress et exemples FR/EN|Retirer filtres ou revenir au fichier précédent ; aucune réécriture des données
M21|Diagnostic temporaire accueil|wp/mu-plugins/koino-diag-frontpage.php|REMOVE|V S16 : diagnostic absent de la liste MU ; retrait recommandé du déploiement normal après tout usage futur, source conservée ; V S19 : absence du fichier confirmée dans les deux racines|SEC-01 SEC-03 OPS-02|P1/F0|0.25-0.5|Diagnostic v1.0.0 livré, résultat inconnu|État interne PHP ; exposition accidentelle ou oubli|Diagnostic terminé ; présence distante à vérifier|Archiver outil et résultat privé ; réactivation contrôlée sur clone seulement
M22|Affichage taille unique|wp/plugins/kh-single-variation-display/|IMPROVE|V S16/F10 : plugin1.0.0 actif ; défauts potentiels mono-option/multi-attribut relevés ; panier NV ; V S19 : fichier staging identique après normalisation et lint réussi ; absent de production|CAT-02 COM-01 UX-02|P1/F1|0.5-2|UX catalogue v1.0.0|Variation/panier ; impossibilité de réinitialiser ou ajouter|Tests mono/multi attributs, rupture, FR/EN et mobiles|Désactiver plugin pour revenir au select natif, conserver produits et variations
M23|Source catalogue et imports|catalog/master.csv ; docs/lot2/*.csv|REFACTOR|V F04/S09 : sources partielles, anciennes taxonomies et SKU incompatibles|CAT-01 CAT-02 DAT-01 DAT-02|P0/F0|2-5|Imports FR et traductions documentés|SKU/IDs/prix/stock par référence ; doublons|Export WC/PLL et source autoritaire arbitrée|Mapping réversible, essai à blanc ; jamais de renumérotation automatique des SKU vendus
M24|Données WC / variantes / taxes|Base staging/prod ; zones et transport|IMPROVE|V S16/S18 :34 produits publiés ; une zone France forfait5/gratuit55, aucune méthode reste du monde malgré promesse UE/DROM ; taxes désactivées ; checkout NV|COM-01 INT-01 ORD-01|P0/F1|1-3|Réglages manuels et doctrine shipping|Prix/commandes/stock ; facturation erronée|Accès WC et règles commerciales validées|Exporter réglages et variations ; rapprocher chaque commande impactée
M25|Paiement Stripe et PayPal|Passerelles officielles et webhooks|IMPROVE|V S16/S18 : Stripe10.9.1 test et configuration requise ; PayPal4.1.2 Compte de test ; transactions/webhooks NV|COM-01 ORD-01 SEC-03|P0/F1|1-3|Passerelles installées selon inventaire|Paiements ; double commande ou confirmation injustifiée|Comptes sandbox et recette idempotence|Ancienne version plugin et paramètres sécurisés ; réconciliation prestataire/commande
M26|SMTP / e-mails commerciaux|FluentSMTP ; Brevo ; wp_mail|IMPROVE|V S16 : FluentSMTP2.3.1 affiche doit être configuré ; transport effectif et délivrabilité NV|COM-01 ARC-03 OPS-01|P0/F1|0.5-2|DNS et service déclarés, notifications documentées|Messages ; absence d'accusés ou envoi réel en test|SMTP sandbox/sink, DNS et destinataires autorisés|Rétablir transport précédent ; file de messages et relance contrôlée
M27|Formulaires FR/EN / leads|Fluent Forms 5–12 ; pages Lot3||V S16 : Fluent Forms6.2.13, huit formulaires5–12 actifs zéro entrée affichée ; définitions/notifications NV|CRM-01 PRV-01 UX-02|P0/F1|1-3|Contact/B2B/B2G/rétractation saisis selon Claude|Leads et consentements ; perte ou destinataire erroné|Export des définitions sans soumissions personnelles|Réimport version connue avec IDs et pages, préserver les soumissions
M28|Rétractation et accusé durable|Formulaires11/12 ; CGV10.3 ; checklist|IMPROVE|V S16/F12 : formulaires11/12 actifs ; promesse CGV existante, accusé durable et parcours non recettés ; V S17 : formulaires rendus FR/EN avec confirmation, aucun envoi|COM-01 PRV-03 REC-01|P0/F1|0.5-2|CGV et formulaire déclarés|Demandes clients ; exercice du droit et preuve|Validation fonctionnelle FR/EN et e-mail|Conserver traces et ancienne définition ; correction ne doit pas effacer demandes
M29|Corpus juridique / identité / origine|docs/lot0/KH-017-documents-legaux/|IMPROVE|V F12/S11 : corpus et ambiguïtés BCDG ; écart doctrine cible ; V S17 : liaisons mentions et cookies manquantes|PRV-01 PRV-02 CAT-02 VIS-02|P0/F1-F2|1-3|Révisions et relecture sourcée déclarées|Engagements publics ; promesse non implémentée|Arbitrage Alain et compétences juridiques|Versions datées archivées ; ne pas altérer conditions acceptées
M30|Cookies / consentements|Complianz ; politiques ; newsletter||V S16 : Complianz7.5.4 actif ; blocage réel/refus/retrait/traceurs NV|PRV-01 PRV-04 ANA-01|P0/F1|0.5-2|Textes et consentements déclarés|Préférences et analytics ; traceurs prématurés|Inventaire réseau et finalités|Conserver preuve des choix ; revenir à configuration connue sans réactiver traceurs refusés
M31|Sauvegardes et restauration|UpdraftPlus ; Drive ; JetBackup|IMPROVE|V S16 : neuf ensembles listés dont09/09 17h57, base daily7/fichiers weekly4, Drive déclaré connecté ; intégrité/restauration NV ; V S19 : JetBackup 32 copies par base KH, dernières09/09 ; 0 archive backup_ directe dans updraft staging ; intégrité et restauration NV|AUD-01 SEC-04 OPS-01 OPS-02 GOV-02|P0/F0|1-3|Sauvegardes historiquement configurées|Toutes données ; perte unique copie staging|Accès archives et clone isolé neutralisé|Drill chronométré, réconciliation commandes, aucun clonage prod vers staging
M32|Déploiement et exports répétables|Procédures KH103/KH107 ; exports non suivis|BUILD|V S05/F02 : pas de release ni export rejouable versionné ; service externe NV|GOV-02 OPS-01 DAT-02|P0/F0|2-5|Procédures manuelles dispersées|Code/config/contenus ; écrasement et dérive|M31 inventaire et mapping IDs|Retour applicatif compatible et archive pré-release ; jamais rollback aveugle de base
M33|Scripts de recette existants|docs/lot1/*tests.ps1 ; *tests.sh|IMPROVE|V F11 : scénarios utiles, TLS désactivé, paramètres sensibles|REC-01 SEC-03 SEO-01|P1/F0|0.5-2|Gates bilingues historiques|Preuves/logs ; faux PASS sécurité|TLS validé, secrets hors arguments/logs|Conserver scénarios et résultats historiques ; nouvelle version revue
M34|Outillage images sharp|tools/package.json ; package-lock.json ; png-to-webp.js|IMPROVE|V S12 : sharp0.33.5, audit high ; usage serveur non établi|SEC-04 SEC-02 OPS-01|P1/F0|0.5-1.5|Convertisseur local et verrou npm|Fichiers locaux ; parsing non fiable, --delete possible|Mise à jour testée sur copies fiables|Conserver sorties antérieures ; pas de conversion avec --delete ; verrou de dépendances versionné
M35|Sécurité serveur / MFA / rôles|Wordfence ; cPanel ; PHP ; permissions|IMPROVE|V S16 : Wordfence9.0.1, intégration Login Security WC inactive,6 mises à jour proposées ; MFA/permissions NV ; V S19 : uploads0777 et wp-config0644 sur les deux sites ; compte système partagé ; protection Basic staging ; exploitation/MFA NV|SEC-01 SEC-03 SEC-04 BO-01|P0/F0-F1|1-3|Hardening déclaré, pas d'inventaire actuel|Système et données ; accès excessifs ou faille version|Accès admin/serveur et liste versions|Sauvegarder configuration ; maintenir MFA et accès de secours contrôlé
M36|Cache / jobs / logs / alertes|LiteSpeed ; WP cron ; Action Scheduler ; hébergeur|IMPROVE|V S16 : LSCache page indisponible, pas de cache objet externe déclaré ;7 échecs fetch_patterns sans callback ; supervision NV ; V S19 : aucun drop-in PHP observé à la racine wp-content staging ; logs supplémentaires dans les cœurs WP, contenu et accès public NV|OPS-01 OPS-02 ARC-03|P0/F1|1-3|Cache et backups déclarés|Sessions/jobs ; panier caché, tâches perdues|Audit configuration et test incident|Revenir aux exclusions/config validées ; conserver jobs et rapprochements
M37|État des comptes clients|WP users ; Woo My Account||V S18 : invité et inscriptions checkout/compte actifs ; récupération, identité et cloisonnement non recettés|ACC-01 ACC-03 SEC-01|P0/F1|1-3|Compte WC prévu ; réalisation actuelle NV|Identités/commandes ; transfert abusif ou verrouillage|Clone anonymisé et deux comptes tests|Préserver IDs clients et commandes ; révoquer sessions de test seulement
M38|Organisations et permissions métier|Module KH éventuel hors dépôt||V S05 : aucun module local ; NV backend ; orientation BUILD si absence confirmée|ACC-02 BO-01 SEC-01|P0/F2|3-7|Hors ancien MVP, aucune livraison locale identifiée|Organisations ; accès croisé et faux signataire|Inventaire distant, modèle ACC/DAT|Fonction désactivable, migrations additives, conserver historique des habilitations
M39|Designs / familles / droits / versions|Catalogue et futur modèle KH||V F04 : modèle dédié absent du dépôt ; NV base|CAT-01 DAT-01 DAT-02 PRD-01|P1/F1-F2|2-5|Catégories/SKU existants à préserver|Relations et droits ; duplication des récits|M23 et décision de schéma|Mapping IDs sauvegardé, modèles extensibles sans écraser données initiales
M40|Custom2D et minimums serveur|Module KH / configurateur non trouvé localement||V S05 : pas de code métier ; NV fonctions externes ; orientation BUILD conditionnelle|CUS-01 CUS-02 CUS-03 UX-01 UX-02|P0-P1/F2|5-12|Page de contact Custom existante, pas preuve d'un configurateur|Configs/fichiers ; seuil50/150 contournable|M38/39/44, API et tests T03/T04|Feature flag fermé ; garder briefs, versions et commandes, aucun envoi industriel automatique
M41|Projects / visualisation / queue|Module KH / prestataire images non identifié||V S05 : aucun endpoint/job local ; NV service distant|PRJ-01 VIS-01 VIS-02 VIS-03 ARC-03|P0-P1/F2|6-15|Aucune livraison de module identifiée|Photos et coûts ; fuite ou génération répétée|Stockage privé, quotas, prototype rendu et repli|Arrêter nouvelles tâches, conserver dossiers, repli manuel sans perdre demandes
M42|Devis et BAT versionnés|Module KH ; approbations||V S05 : aucune machine d'états locale ; clauses BAT seules|QUO-01 BAT-01 BAT-02 DAT-02|P0/F2|5-12|Clause contractuelle rédigée, module NV|Accords immuables ; fabrication sur mauvaise version|Identité, droits, fichiers privés, contrôle concurrence|Ne jamais effacer accords ; désactiver nouvelle libération, restaurer code compatible
M43|Production / B2G / expéditions|Dossiers fournisseur ; libération KH||NV : aucun workflow numérique identifié ; absence locale seulement|PRO-01 ORD-01 BO-02|P0/F2|3-8|Traitement offline prévu historiquement|BAT/BC/paiement/lot ; production injustifiée|M42 et conditions commerciales validées|Suspendre nouveaux ordres sans annuler silencieusement ceux en cours ; journal manuel
M44|Stockage privé / uploads / purge|Serveur/stockage objet non identifié||NV service ; aucune implémentation locale ni DPA fournis|SEC-02 SEC-03 PRV-02 PRV-03 DAT-02|P0/F2|3-8|Uploads explicitement hors ancien MVP|Photos/BAT ; liens publics permanents et conservation excessive|Architecture stockage, rôles, scanner et sandbox|Fermer nouveaux uploads ; garder accès privé aux contrats et réappliquer purges après restauration
M45|Suivi commercial / WhatsApp|Dossiers et canal autorisé||NV service ; aucun journal applicatif local identifié|CRM-01 CRM-02 PRV-04|P1/F2|2-5|Formulaires de captation existants déclarés|Contacts ; relance non autorisée ou fuite vidéo|Consentement distinct et opérateur KH|Arrêter relances, conserver historique/preuves et canal e-mail autorisé
M46|Back-office et attention opérateur|Module KH / capacités métier||NV service ; aucune vue dossier versionnée|BO-01 BO-02 BO-03|P0-P1/F2|3-7|Administration WC prévue, fonctions KH non identifiées|Dossiers/rôles ; modification non tracée|M38–45 et opérateur commercial|Feature flags, rôles minimaux et conservation des journaux
M47|Contrats API et schéma KH versionnés|Documentation/code du dépôt|BUILD|V S05 : pas de contrats/migrations KH versionnés ; cible ARC/DAT|ARC-01 ARC-02 ARC-03 DAT-01 DAT-02|P0-P1/F0-F2|3-7|Aucun livrable API métier local|Interfaces ; confiance prix client et concurrence|ADR, inventaire distant et prototype|Versionner contrats ; compatibilité descendante, migrations additives et contrôles totaux
M48|Kaïro / éditions / QR durables|docs/kairo-bd-recit-et-produit.md ; catalogue|IMPROVE|V S15 : récit15 épisodes et quatre produits sources ; éditions/QR NV|KAI-01 KAI-02 ANA-02|P1/F1-F2|2-5|Récit et décisions antérieures documentés|URLs imprimées/contenus ; liens périssables|Édition FR/EN, droits et distributeur validés|Conserver QR et redirections ; ne jamais réattribuer identifiants d'aventure
M49|Analytics et indicateurs|Plausible et commerce||V S16 : aucun plugin Plausible dans14 actives ; service/injection externe et événements NV|ANA-01 ANA-02 PRV-04|P1/F1-F2|1-3|Doctrine WC Orders source de vérité|Événements ; double purchase et données personnelles|Consentements, commandes test et réconciliation|Désactiver collecteur défaillant, garder commerce intact et versions du plan
M50|RGPD et cycle de vie|Politiques / registre / sous-traitance|IMPROVE|V S11/S18 : politique comptes3 ans ; champs de conservation WC vides ; procédure hors écran et purge effective NV|PRV-01 PRV-02 PRV-03 PRV-04 OPS-02|P0/F1-F2|1-3|Corpus FR/EN et checklist|Données personnelles ; promesses non appliquées|Prestataires/rôles/finalités et validation compétente|Conserver demandes/archives nécessaires ; documenter purges et exceptions de litige
M51|Passport / My Collection|Option future||NV implémentation hors dépôt ; P2 option, pas de chantier engagé|FID-01|P2/F3|2-5|Aucune livraison identifiée|Possession et compte ; fausse certification|GO usage/marge, preuve de possession, identité unique|Désactiver option sans affecter comptes/commandes ; export des inscriptions
M52|World Gallery / modération|Option future||NV implémentation hors dépôt ; aucun transfert automatique des photos|GAL-01 GAL-02 PRV-04 SEC-02|P2 et P0 activation/F3|3-7|Aucune livraison identifiée|Photos/GPS/droits ; publication indue|GO, droits, modération, purge et retrait|Dépublier médias concernés, révoquer liens et conserver preuve des consentements
M53|Extensions et kits DIY|Dossiers produit non inventoriés||NV dossiers/essais ; option, pas de fabrication déduite du logiciel|PRD-01 DIY-01 DIY-02|P2-P3/F3-F4|0.5-2|Pistes gamme, aucun essai démontré|Produits/lot ; promesse de pose ou sécurité sans essai|GO produit, essais physiques et responsabilités|Retrait contrôlé de référence, traçabilité commandes et lots ; pas de suppression d'historique
M54|App native / AR|Aucun projet natif dans le dépôt||V S05 : absence de chantier local ; option non engagée, aucune décision de reprise nécessaire|ARC-03 UX-01|P3/F4|0-0|Aucune implémentation native identifiée|Périmètre/coûts ; infrastructure prématurée|GO distinct et preuve de besoin|Aucun changement à effectuer ; conserver compte/API communs si option future
M55|Coûts / licences / capacité équipe|Contrats hébergeur/plugins/services||NV factures/renouvellements, capacité réelle et budgets ; vieux objectifs non probants ; V S19 : six lunes gratuites disponibles ; quota réel, licences, factures et coûts récurrents restent NV|OPS-01 ARC-02 PRD-01|P0/F0|0.5-1.5|Stack et échéances déclarées|Exploitation ; licence expirée et charge sous-estimée|Alain, prestataires et responsable technique|Conserver factures/licences privées, prévoir export et remplacement seulement après comparaison
M56|Recette transverse et traçabilité|Tests T01–T14 ; registre d'exigences|BUILD|V S05 : pas de registre exhaustif préalable ; présent dossier amorce la traçabilité, scénarios d'exécution restent à construire|AUD-01 AUD-02 REC-01|P0/F0-F2|1-3|Gates i18n partiels réutilisables|Preuves ; faux terminé sans scénario métier|Environnements neutres et exigences validées|Conserver résultats par version ; ne pas écraser les échecs historiques
M57|Factures PDF et numérotation|PDF Invoices & Packing Slips||V S16 :5.16.1 actif ; paramétrage fiscal, numérotation, accès factures et émission NV|COM-01 ORD-01 PRV-02|P0/F1|0.5-2|Extension installée, contribution précise non attribuable|Factures et identité ; doublons, mentions ou accès erronés|Commandes test et validation paramètres/documents|Préserver numéros et factures émises ; retour plugin compatible sans régénération aveugle
'''
rows=[]
for line in DATA.strip().splitlines():
    vals=line.split('|')
    assert len(vals)==12,(len(vals),line)
    ident,name,path,decision,proof,req,priority,charge,claude,data,deps,rollback=vals
    low,high=map(float,charge.split('-'))
    row=dict(id=ident,composant=name,chemin_ou_service=path,version_deployee='Non vérifiée sauf précision dans la preuve ; voir rapport §5',fonction=name,contribution_claude_connue=claude,exigences=req.split(),constat_et_preuve=proof,couverture_tests='Lecture/inventaire local, HTTP public, UI S16–S18 et serveur S19 selon composant ; lint de trois PHP et checksums cœur exécutés ; transactions et restauration non exécutées',decision=decision or None,statut_decision='Recommandation locale conditionnelle ; non appliquée' if decision else 'Non attribuée : accès/inventaire requis ; inconnue ne signifie pas BUILD',justification=proof,dependances=deps,criticite_phase=priority,donnees_affectees_et_risque=data,charge_basse_j6h=low,charge_haute_j6h=high,hypotheses_charge='Estimation initiale de la prochaine intervention décrite, hors attente externe ; non additive aux autres lignes, à réestimer après F0. Pour options : étude/pilote seulement, aucun engagement.',ordre=int(ident[1:]),responsable='Responsable technique à désigner ; Alain pour données/décisions métier',approbateur='Alain (métier) et responsable technique (exploitation), non acquis',procedure_retour=rollback)
    if ident=='M01': row['version_deployee']='Git main d3073dafb0b11c9866e23a02ecc357e0b7ca0cdd, pas une version serveur'
    if ident=='M07': row['version_deployee']='Production et staging WP7.1 via WP-CLI ; checksums cœur réussis avec avertissements fichiers supplémentaires S19'
    if ident=='M11': row['version_deployee']='Production : Kadence1.5.0 WP-CLI S19 ; staging : Kadence1.5.2 état WC S16'
    if ident=='M12': row['version_deployee']='Enfant production1.0.1 ; dépôt et staging1.1.0 annoncés, chargements CSS différents'
    if ident=='M34': row['version_deployee']='Outil local sharp0.33.5 ; aucun déploiement Web établi'
    versions={'M08':'Staging WooCommerce 11.1.0 ; base 11.1.0-1 ; HPOS actif', 'M09':'Staging Polylang 3.8.7 et Polylang for WooCommerce 2.2.4', 'M10':'Staging SEOPress 10.2', 'M19':'Staging MU racine 1.1.0', 'M20':'Dépôt 1.1.0 ; absent de la liste MU staging', 'M21':'Dépôt 1.0.0 ; absent de la liste MU staging', 'M22':'Staging 1.0.0', 'M25':'Staging Stripe 10.9.1 et PayPal 4.1.2', 'M26':'Staging FluentSMTP 2.3.1', 'M27':'Staging Fluent Forms 6.2.13', 'M28':'Fluent Forms 6.2.13 ; formulaires 11 et 12', 'M30':'Staging Complianz 7.5.4', 'M31':'Staging UpdraftPlus 1.26.7', 'M35':'Staging Wordfence 9.0.1 ; PHP 8.3.33', 'M36':'Staging LiteSpeed Cache 7.9.1 ; Action Scheduler 4.0.0', 'M57':'Staging PDF Invoices & Packing Slips 5.16.1'}
    if ident in versions: row['version_deployee']=versions[ident]+' (écran authentifié S16 ; comparaison distante limitée aux chemins explicités S19)'
    rows.append(row)
assert len(rows)==len(set(r['id'] for r in rows))
(OUT/'MATRICE-REPRISE.json').write_text(json.dumps({'document':'KH2027-AUD-20260910','version':'0.5','baseline':'d3073dafb0b11c9866e23a02ecc357e0b7ca0cdd','date':'2026-09-10','unite_charge':'jours-personne de 6h, non additifs','composants':rows},ensure_ascii=False,indent=2),encoding='utf-8')
counts=collections.Counter(r['decision'] or 'NON ATTRIBUÉE' for r in rows)
md=['# Matrice de reprise KH2027 — v0.5','', 'Base : `d3073da`, audit du 10 septembre 2026. [Rapport et preuves](RAPPORT-AUDIT-KH2027.md). [Données complètes structurées](MATRICE-REPRISE.json).', '', '**57 composants couverts. G0 non acquis. Aucune décision exécutée.** Les classes portent sur le périmètre explicitement observé ; une classe vide signifie non attribuée, et non BUILD. Un KEEP d’actif/archive ne certifie ni ses droits ni une intégration serveur. Les BUILD concernent des livrables manquants dans le dépôt, sans présumer des outils externes. REMOVE M21 vise le diagnostic dans le déploiement normal après usage, sans supprimer sa source.', '', 'Les six classes sont disponibles : KEEP conserver, IMPROVE améliorer localement, REFACTOR préserver le comportement en corrigeant la structure, REPLACE remplacer après comparaison/migration/retour, REMOVE retrait maîtrisé, BUILD construire après preuve d’absence. **Aucun REPLACE justifié à ce stade.**', '', 'Répartition : '+', '.join(f'{k} {v}' for k,v in sorted(counts.items()))+'.', '', 'Les fourchettes couvrent les interventions décrites et se chevauchent ; elles ne constituent pas un devis ni une somme de budget. L’ordre est un identifiant de lecture ; la priorité opérationnelle et les dépendances priment (rapport §10). Responsable technique à désigner, Alain approbateur métier : aucune validation supposée.', '', '| ID | Composant | Classe proposée | Priorité / phase | Charge j6h | Preuve / réserve |','|---|---|---|---|---|---|']
for r in rows:
    md.append(f"| [{r['id']}](#{r['id'].lower()}) | {r['composant']} | {r['decision'] or 'Non attribuée'} | {r['criticite_phase']} | {r['charge_basse_j6h']:g}–{r['charge_haute_j6h']:g} | {r['constat_et_preuve']} |")
md+=['','## Fiches complètes','', 'Toutes les fiches reprennent les champs AUD-02 p.10. V = vérifié dans cet audit ; H = historique déclaré ; NV = non vérifié. Les identifiants S01–S19 et F01–F16 renvoient au registre et aux constats du rapport. Pour toutes les fiches : date 10/09/2026, base locale d3073da ; les observations HTTP ont leur timestamp dans S06.']
for r in rows:
    md += ['',f"### {r['id']}",'',f"**{r['composant']} — {r['decision'] or 'classe non attribuée'}**",'',f"- Chemin/service : `{r['chemin_ou_service']}`. Fonction : {r['fonction']}.",f"- Version déployée : {r['version_deployee']}.",f"- Contribution Claude connue : {r['contribution_claude_connue']}.",f"- Exigences : {', '.join(r['exigences'])}. Criticité/phase : {r['criticite_phase']}.",f"- Constat/preuve et justification : {r['constat_et_preuve']}.",f"- Couverture des tests : {r['couverture_tests']}.",f"- Décision : {r['statut_decision']}.",f"- Dépendances : {r['dependances']}.",f"- Données affectées / risque : {r['donnees_affectees_et_risque']}.",f"- Charge basse/haute : {r['charge_basse_j6h']:g}–{r['charge_haute_j6h']:g} j6h. {r['hypotheses_charge']}",f"- Ordre de lecture : {r['ordre']}. Responsable : {r['responsable']}. Approbateur : {r['approbateur']}.",f"- Retour proposé (non testé) : {r['procedure_retour']}."]
(OUT/'MATRICE-REPRISE.md').write_text('\n'.join(md)+'\n',encoding='utf-8')
requirements=json.loads((OUT/'evidence/local-checks.json').read_text('utf-8'))['requirements']
coverage={q:[r['id'] for r in rows if q in r['exigences']] for q in requirements}
assert all(coverage.values()),[q for q,v in coverage.items() if not v]
ref=(OUT/'evidence/referentiel-extrait.txt').read_text('utf-8')
pages={}
for part in re.split(r'=== PAGE (\d+) ===',ref)[1:][::2]: pass
splits=re.split(r'=== PAGE (\d+) ===',ref)
for i in range(1,len(splits),2):
    page=int(splits[i]); text=splits[i+1]
    for q in requirements:
        if re.search(re.escape(q)+r'\s*•',text): pages.setdefault(q,page)
lines=['# Couverture KH2027 v3.0 et recette — 10 septembre 2026','', '**58 exigences explicites identifiées, toutes reliées à la matrice. Aucun PASS serveur implicite.** Les exigences ne sont pas réalisées du seul fait de ce tableau. Voir le [rapport](RAPPORT-AUDIT-KH2027.md) et les [fiches de composants](MATRICE-REPRISE.md).','', '| Exigence | Page PDF | Composants | État de vérification |', '|---|---|---|---|']
for q,ids in coverage.items():
    status='Cible ; preuves locales partielles / exécution serveur NV'
    if q=='AUD-01': status='Partiel : audit accessible produit ; comparaison complète et restauration non réalisées'
    if q=='AUD-02': status='Matrice produite ; classes des services inconnus laissées non attribuées'
    if q.startswith(('FID','GAL','DIY','PRD')): status='Option cible ; aucune activation ni conformité supposée'
    lines.append(f"| {q} | {pages.get(q,'voir registre')} | {', '.join(ids)} | {status} |")
tests=[('T01','Audit dépôt/site/Claude','Partiel : rapport et preuves ; G0 non acquis','M01–M57'),('T02','Achat mobile FR/EN','Non exécuté : sandbox et destinataires de test requis','M08,M24,M25,M26'),('T03','Seuils49/50,149/150 et mélanges','Non exécuté : module métier non identifié','M40'),('T04','Anonyme mobile vers compte et PC','Non exécuté : projet/identité à inventorier','M37,M38,M40,M41'),('T05','Simulation, variantes, timeout, quotas','Non exécuté : fournisseur/module non identifié','M41'),('T06','BAT V1 remplacé par V2','Non exécuté : workflow absent du dépôt, distant NV','M42'),('T07','Webhook doublé et retour navigateur absent','Non exécuté : sandbox et événements requis','M25'),('T08','Paiement reçu mais BAT absent','Non exécuté : verrou de production à éprouver','M42,M43'),('T09','B2G artistique/administratif','Non exécuté : dossiers et conditions à vérifier','M38,M43'),('T10','Accès croisé et lien expiré','Non exécuté : comptes de test et stockage privé requis','M35,M37,M38,M44'),('T11','Refus cookies/retrait/purge','Non exécuté : services et préférences à vérifier','M30,M44,M45,M50'),('T12','QR FR/EN et changement de slug','Non exécuté : registre QR non fourni','M48'),('T13','Restauration et retour sans perte','Non exécuté : archive actuelle et clone isolé requis','M31,M32'),('T14','Rôles positifs/négatifs','Non exécuté : matrice permissions et comptes de test requis','M35,M38,M46')]
lines+=['','## Recette normative T01–T14 (PDF p.30)','','| Test | Scénario | Résultat présent | Composants |','|---|---|---|---|']
for t in tests: lines.append('| '+' | '.join(t)+' |')
lines+=['','## Compléments transverses sans identifiant propre','','- Économie (PDF p.7) : coût rendu, contribution, marge Custom, capacité humaine et coûts/licences à documenter ; M55. Aucune prévision financière validée.', '- Processus produit et droits (p.3,6,29) : M05/M18/M39/M53. Aucune preuve d’essai physique ou de droit déduite des images.', '- Navigation, absence de pose KH, exactitude de l’origine et phasage : écarts rapport §7 ; M03/M16/M29/M40/M41/M53.', '- Les modèles et valeurs de conservation/performance/calendrier proposés restent à valider ; les P0 de confidentialité s’appliquent dès l’activation d’une option.']
(OUT/'COUVERTURE-EXIGENCES.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
print(json.dumps({'components':len(rows),'requirements':len(requirements),'classes':counts,'unmapped':[]},ensure_ascii=False))
